language: python
python:
- '2.7'
install: pip install -t lib -r requirements.txt
script:
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee
  -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install google-cloud-sdk
- openssl aes-256-cbc -K $encrypted_a93f90b5a47b_key -iv $encrypted_a93f90b5a47b_iv -in service-account-key.json.enc -out service-account-key.json -d
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1
- gcloud auth activate-service-account --key-file service-account-key.json
- APP_VERSION=$(git describe | tr '.' '-')
- gcloud --project=superb-binder-156720 app deploy --version=$APP_VERSION --no-promote app.yaml
